[theme]
base = "dark"
primaryColor = "#ffffff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#121212"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = true

[layout]
wideMode = true